server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  application:
    name: Order-Service

      #Register with eureka server configuration
      #eureka:
      #client:
      # register-with-eureka: true
      #fetch-registry: true
      #service-url:
    #defaultZone: http://localhost:8761/eureka/
    #instance:
    #hostname: localhost


